### ISSUE TITLE
trouble creating jobs with one label

### ISSUE THREAD

**Issue by andrewschoen** [ceph/mita#87]
When we changed the jenkins-job-builder job to use a single label ``small`` I started seeing errors like these in the mita log.

```
[2016-09-12 17:46:59,177: INFO/Worker-1] found stuck task with name: jenkins-job-builder
[2016-09-12 17:46:59,178: INFO/Worker-1] reason was: All nodes of label ?small? are offline
[2016-09-12 17:46:59,178: WARNING/Worker-1] unable to match a suitable node
[2016-09-12 17:46:59,179: WARNING/Worker-1] will infer from builtOn
[2016-09-12 17:46:59,179: INFO/Worker-1] determined job name as:
[2016-09-12 17:46:59,191: ERROR/MainProcess] Task async.check_queue[8819be85-a933-4f7e-a8e8-c6c968cb5210] raised unexpected: NotFoundException('Requested item could not be found',)
Traceback (most recent call last):
  File "/opt/mita/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/mita/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/mita/src/mita/mita/async.py", line 152, in check_queue
    job_id = conn.get_job_info(job_name)['nextBuildNumber']-1
  File "/opt/mita/local/lib/python2.7/site-packages/jenkins/__init__.py", line 272, in get_job_info
    self._build_url(JOB_INFO, locals())
  File "/opt/mita/local/lib/python2.7/site-packages/jenkins/__init__.py", line 361, in jenkins_open
    raise NotFoundException('Requested item could not be found')
NotFoundException: Requested item could not be found
```

I'm unsure of the actual problem here, but changing jenkins-job-builder back to using ``small && trusty`` seems to have unstuck mita.

**Comment by alfredodeza** [comment]
This line right here is surprising:

    [2016-09-12 17:46:59,179: INFO/Worker-1] determined job name as:

That means there is no job name really, and that is why that `NotFoundException` is getting raised: there is no job that matches that name

**Comment by alfredodeza** [comment]
The actual information needed to fix this (added log output):

    [2016-09-13 04:03:28,970: WARNING/Worker-1] could not determine job_name
    [2016-09-13 04:03:28,970: WARNING/Worker-1] {u'url': u'https://jenkins.ceph.com/job/jenkins-job-builder/', u'color': u'blue', u'_class': u'hudson.model.FreeStyleProject', u'name': u'jenkins-job-builder'}
    [2016-09-13 04:03:28,986: ERROR/MainProcess] Task async.check_queue[01ce1ad3-6083-48c4-84fd-ea0f760592e2] raised unexpected: NotFoundException('Requested item could not be found',)

**Comment by alfredodeza** [comment]
Another issue found here is that commit 2497d4f4 forgets to include a return if a single label is found.
